[package]
name = "wallet"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = { workspace = true }
libsecp256k1 = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
aes-gcm = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }